version: "3.4"

services:
  diaspora:
    build:
      context: .
      dockerfile: Dockerfile.diaspora
      args:
        EXT_UID: "${EXT_UID}"
        EXT_GID: "${EXT_GID}"
    image: diaspora:dev-latest
