version: "3.4"

x-diaspora-base: &diaspora-base
  image: diaspora:dev-latest
  volumes:
    - "${DIASPORA_PATH}:/home/diaspora/diaspora:rw"

x-diaspora-db: &diaspora-db
  depends_on:
    - "${DIASPORA_DOCKER_DB}"

volumes:
  postgresql_data:
  mysql_data:

services:
  diaspora-bundle:
    << : *diaspora-base
    command: /bin/sh -c "script/configure_bundler && bin/bundle install --full-index"

  diaspora-migrations:
    << : *diaspora-base
    << : *diaspora-db
    command: /bin/sh -c "bin/rake db:create db:migrate"

  diaspora:
    << : *diaspora-base
    << : *diaspora-db
    ports:
      - 8080:3000

  postgresql:
    image: postgres:9.6
    ports:
      - 55432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql

  mysql:
    image: mysql:5.7
    ports:
      - 53306:3306
    volumes:
      - mysql_data:/var/lib/mysql
