version: "3.4"

volumes:
  postgresql_data:
  mysql_data:

services:
  diaspora:
    build:
      context: .
      dockerfile: Dockerfile.diaspora
    image: diaspora:dev-latest
    volumes:
      - "${DIASPORA_PATH}:/home/diaspora/diaspora:rw"
    ports:
      - 8080:3000
    depends_on:
      - "${DIASPORA_DOCKER_DB}"

  postgresql:
    image: postgres:10.3
    ports:
      - 55432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql

  mysql:
    image: mariadb:10.2
    ports:
      - 53306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
